Make aws-ec2-spot-price-stats more robust
Signed-off-by: Tim Friske <me@tifr.de>

diff --git a/aws/bin/aws-ec2-spot-price-stats b/aws/bin/aws-ec2-spot-price-stats
--- a/aws/bin/aws-ec2-spot-price-stats
+++ b/aws/bin/aws-ec2-spot-price-stats
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-# AWS EC2 Lifecycle command
-# =========================
+# AWS EC2 Spot Prices Stats command
+# =================================
 # Tim Friske <me@tifr.de>
 #
 # Prints the minimum (min), maximum (max), average (avg), median (mdn) and
@@ -19,20 +19,24 @@
 #
 # Deps:: aws, bash, env, jq
 
+# Ensure fail-fast script execution.
 shopt -os nounset errexit errtrace pipefail
 
+# Input parameters and validation:
 : "${aws_region:="${AWS_REGION:-}"}"
 : "${aws_region:="${AWS_DEFAULT_REGION:-}"}"
 : "${aws_region:="$(aws configure get region)"}"
 : "${aws_region:?AWS region required}"
+: "${@:?AWS EC2 instance types required}"
 
 aws_ec2_instance_types=()
-for aws_ec2_it in "${@:?AWS EC2 instance types required}"; do
+for aws_ec2_it in "${@}"; do
   IFS=, read -r -a aws_ec2_its <<< "${aws_ec2_it}"
   aws_ec2_instance_types+=("${aws_ec2_its[@]}")
 done
 
-read -d '' -r aws_ec2_spot_price_stats_query <<'AWS_EC2_SPOT_PRICE_STATS_QUERY' || true
+# Read multi-line jq script into variable for legibility.
+read -d '' -r jq_stats_query <<'JQ_STATS_QUERY' || true
   def avg:add/length;
   def mdn:sort|[.[length/2|ceil|-.,.-1]/2?]|add;
   def rnd($dp):.*pow(10;$dp)|round/pow(10;$dp);
@@ -52,10 +56,10 @@ read -d '' -r aws_ec2_spot_price_stats_query <<'AWS_EC2_SPOT_PRICE_STATS_QUERY' 
     min:min,max:max,avg:avg|rnd(4),mdn:mdn|rnd(4),cnt:length}))
   | map_values({per:.,all:to_entries|[.[].value]|stat})
   | {per:.,all:to_entries|[.[].value.all]|stat}
-AWS_EC2_SPOT_PRICE_STATS_QUERY
+JQ_STATS_QUERY
 
 aws ec2 describe-spot-price-history \
   --region "${aws_region}" \
   --product-descriptions Linux/UNIX \
   --instance-types "${aws_ec2_instance_types[@]}" \
-  | jq "${aws_ec2_spot_price_stats_query}"
+  | jq "${jq_stats_query}"
