Fix/disable ShellCheck linter issues
Signed-off-by: Tim Friske <me@tifr.de>

diff --git a/kubernetes/bin/k8s-mount-pvc b/kubernetes/bin/k8s-mount-pvc
--- a/kubernetes/bin/k8s-mount-pvc
+++ b/kubernetes/bin/k8s-mount-pvc
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # K8S Mount PVC
 # =============
@@ -18,7 +18,8 @@
 #
 # Deps:: env, kubectl, sh
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 : "${1:?Persistent volume claim required}"
 
@@ -55,8 +56,7 @@ kubectl wait --for=condition=Ready --timeout=30s "pod/k8s-mount-pvc-${pvc}"
 
 echo "Logging into Kubernetes Pod 'k8s-mount-pvc-${pvc}', Container 'mount' ..."
 echo "Using 'ash' as an interactive shell for the login session ..."
-(kubectl exec "k8s-mount-pvc-${pvc}" --container=mount --stdin=true --tty=true \
-  -- ash) || true
+(kubectl exec "k8s-mount-pvc-${pvc}" --container=mount --stdin=true --tty=true -- ash) || true
 
 echo "Deleting Kubernetes Pod 'k8s-mount-pvc-${pvc}' in background ..."
-kubectl delete "pod/k8s-mount-pvc-${pvc}" 2>&1  >/dev/null &
+kubectl delete "pod/k8s-mount-pvc-${pvc}" &>/dev/null &
diff --git a/ls/bin/llvd b/ls/bin/llvd
--- a/ls/bin/llvd
+++ b/ls/bin/llvd
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Ls command
 # ==========
@@ -9,8 +9,10 @@
 # information. Sorts files by alphanumerical version numbers in
 # descending order.
 #
-# Deps:: env, ls, sh
+# Deps:: bash, env, ls
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-ls ${LS_X_OPTIONS:-} --format=long --sort=version --reverse "${@}"
+read -r -a ls_x_options <<< "${LS_X_OPTIONS:-}"
+ls "${ls_x_options[@]}" --format=long --sort=version --reverse "${@}"
diff --git a/util/bin/diff-dirs b/util/bin/diff-dirs
--- a/util/bin/diff-dirs
+++ b/util/bin/diff-dirs
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Diff Directories command
 # ========================
@@ -9,8 +9,10 @@
 # differences in content between the actual files because that would
 # result in cognitive overload.
 #
-# Deps:: diff, env, sh
+# Deps:: bash, diff, env
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-diff ${DIFF_X_OPTIONS:-} --recursive --brief "${@}"
+read -r -a diff_x_options <<< "${DIFF_X_OPTIONS:-}"
+diff "${diff_x_options[@]}" --recursive --brief "${@}"
diff --git a/util/bin/du-summary b/util/bin/du-summary
--- a/util/bin/du-summary
+++ b/util/bin/du-summary
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Disk Usage Summary command
 # ==========================
@@ -6,8 +6,10 @@
 #
 # Summarize the disk usage of the current directory.
 #
-# Deps:: du, env, sh
+# Deps:: bash, du, env
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-du ${DU_X_OPTIONS:-} --summarize "${@}"
+read -r -a du_x_options <<< "${DU_X_OPTIONS:-}"
+du "${du_x_options[@]}" --summarize "${@}"
diff --git a/util/bin/file-backup b/util/bin/file-backup
--- a/util/bin/file-backup
+++ b/util/bin/file-backup
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # File Backup command
 # ===================
@@ -14,17 +14,18 @@
 # Think about aliasing this helper program as `fb` (`file-backup`)
 # should you be using it frequently.
 #
-# Deps:: cp, env, sh
+# Deps:: bash, cp, env
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 main() {
-  if [ ! -f "${1:-}" ]; then
+  if [[ ! -f "${1:-}" ]]; then
     echo 'usage: file-backup <file> [<file>|<folder>]'
     exit 1
   fi
   # Same file? Prevent _cp: './foo' and 'foo' are the same file_.
-  if [ "${1}" -ef "${2:-${1}}" ]; then
+  if [[ "${1}" -ef "${2:-${1}}" ]]; then
     cp --force --backup=numbered --verbose -- "${1}" "${1}"
   else
     cp --force --backup=numbered --verbose -- "${1}" "${2:-${1}}"
diff --git a/util/bin/file-view b/util/bin/file-view
--- a/util/bin/file-view
+++ b/util/bin/file-view
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # File View command
 # =================
@@ -22,7 +22,8 @@
 #
 # Deps:: env, less, more, sh
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 prog="${0##*/}"
 
@@ -30,17 +31,18 @@ PAGER="${PAGER:-$(command -v less)}"
 PAGER="${PAGER:-$(command -v more)}"
 
 main() {
-  if [ "${#}" -ne 1 ]; then
+  if (( "${#}" != 1 )); then
     echo >&2 "${prog}: usage: ${prog} <file (on path)>"
     exit 1
   fi
   local file="${1}"
-  if [ -f "${file}" ]; then
+  if [[ -f "${file}" ]]; then
     "${PAGER}" -- "${file}"
     exit
   fi
-  local on_path="$(command -v "${file}")"
-  if [ -n "${on_path:+x}" ]; then
+  local on_path
+  on_path="$(command -v -- "${file}")"
+  if [[ -n "${on_path:+x}" ]]; then
     "${PAGER}" -- "${on_path}"
     exit
   fi
diff --git a/util/bin/luks-encrypt b/util/bin/luks-encrypt
--- a/util/bin/luks-encrypt
+++ b/util/bin/luks-encrypt
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # LUKS Device Encryption command
 # ==============================
@@ -18,19 +18,22 @@
 # program with `sudo`, `su` etc. this time authenticating as a user
 # with appropriate permissions.
 #
-# Deps:: cryptsetup, env, sh
+# Deps:: bash, cryptsetup, env
 
-ensure_block_special_file() {
-    local file="${1:-${file:?'required'}}"
-    if [ ! -b "${file}" ]; then
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
+
+function ensure_block_special_file {
+    local file="${1:-${file:?required}}"
+    if [[ ! -b "${file}" ]]; then
         echo >&2 Given file must be a block special device! Aborting...
         exit 1
     fi
 }
 
 # Creates a LUKS encrypted container with on-disk format version 2.
-modern_crypt() {
-    local device="${1:-${device:?'required'}}"
+function modern_crypt {
+    local device="${1:-${device:?required}}"
     ensure_block_special_file "${device}"
     local label="${2:-${label:-}}"
     cryptsetup \
@@ -47,8 +50,8 @@ modern_crypt() {
 }
 
 # Creates a LUKS encrypted container with on-disk format version 1.
-compat_crypt() {
-  local device="${1:-${device:?'required'}}"
+function compat_crypt {
+  local device="${1:-${device:?required}}"
   ensure_block_special_file "${device}"
   cryptsetup \
     --verbose \
@@ -62,10 +65,9 @@ compat_crypt() {
 }
 
 main() {
-  local style="${1:-${style:?'required'}}"
-  local device="${2:-${device:?'required'}}"
+  local style="${1:-${style:?required}}"
+  local device="${2:-${device:?required}}"
   local label="${3:-${label:-}}"
-  shift $(($#-($#${1+-1}${2+-1}${3+-1})))
   case "${style}" in
   modern) modern_crypt "${device}" "${label}" ;;
   compat) compat_crypt "${device}" ;;
diff --git a/util/bin/nth b/util/bin/nth
--- a/util/bin/nth
+++ b/util/bin/nth
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Nth command
 # ===========
@@ -6,13 +6,14 @@
 #
 # Print the nth line read from standard input or given file.
 #
-# Deps:: env, sed, sh
+# Deps:: bash, env, sed
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 main() {
   : "${1:?usage: nth NUM [FILE]}"
-  local num="$((${1}))"
+  local num="$(("${1}"))"
   local file="${2:--}"
   # Exit when line reached to save CPU cycles.
   # Faster than:
diff --git a/util/bin/peek b/util/bin/peek
--- a/util/bin/peek
+++ b/util/bin/peek
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Peek command
 # ============
@@ -7,8 +7,9 @@
 # Print the output of one command that is piped as input to another
 # command to the standard error stream in order to have a peek at it.
 #
-# Deps:: cat, env, sh, tee
+# Deps:: bash, cat, env, tee
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 tee >(cat >&2)
