Abort if Mktar is called under unknown name
Inform the caller about all known names under which the _Mktar_ program
may be invoked, namely `mktar`, `mktbz`, `mktgz` and `mktxz`.

Signed-off-by: Tim Friske <me@tifr.de>

diff --git a/util/mktar b/util/mktar
--- a/util/mktar
+++ b/util/mktar
@@ -23,6 +23,12 @@ function mktar {
   local archive="${1%/}"
   echo '# Archiving files ...'
   echo '# ==================='
+  case "$program" in
+    *)
+      echo 'error: must be one of mktar, mktbz, mktgz, mktxz!'
+      exit 2
+      ;;
+  esac
 }
 
 mktar "$@"
