Change interpreter from POSIX Dash to Bash shell
Signed-off-by: Tim Friske <me@tifr.de>

diff --git a/git/command/branch/bin/git-b b/git/command/branch/bin/git-b
--- a/git/command/branch/bin/git-b
+++ b/git/command/branch/bin/git-b
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Branch command
 # ==================
@@ -7,8 +7,9 @@
 # Show the current branch name by default unless another Git branch
 # operation is chosen by passing arguments.
 #
-# Deps:: env, git-branch, sh
+# Deps:: bash, env, git-branch
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git branch "${@:---show-current}"
diff --git a/git/command/branch/bin/git-bdm b/git/command/branch/bin/git-bdm
--- a/git/command/branch/bin/git-bdm
+++ b/git/command/branch/bin/git-bdm
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Branch command
 # ==================
@@ -7,9 +7,10 @@
 # Delete each merged local branch except the current one because it
 # cannot be deleted.
 #
-# Deps:: env, git-bd, git-for-each-ref, sh, xargs
+# Deps:: bash, env, git-bd, git-for-each-ref, xargs
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git for-each-ref \
   --format='%(if:notequals=*)%(HEAD)%(then)%(refname:lstrip=2)%(end)' \
diff --git a/git/command/branch/bin/git-be b/git/command/branch/bin/git-be
--- a/git/command/branch/bin/git-be
+++ b/git/command/branch/bin/git-be
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Branch command
 # ==================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-branch, sh
+# Deps:: bash, env, git-branch
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git branch --edit-description "${@}"
diff --git a/git/command/branch/bin/git-bg b/git/command/branch/bin/git-bg
--- a/git/command/branch/bin/git-bg
+++ b/git/command/branch/bin/git-bg
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Branch command
 # ==================
@@ -7,9 +7,10 @@
 # Lists each local branch whose remote tracking branch is gone on a new
 # line.
 #
-# Deps:: env, git-for-each-ref, sed, sh, xargs
+# Deps:: bash, env, git-for-each-ref, sed, xargs
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git for-each-ref \
     --format='%(if:equals=[gone])%(upstream:track)%(then)%(refname:short)%(end)' \
diff --git a/git/command/branch/bin/git-bgd b/git/command/branch/bin/git-bgd
--- a/git/command/branch/bin/git-bgd
+++ b/git/command/branch/bin/git-bgd
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Branch command
 # ==================
@@ -6,8 +6,9 @@
 #
 # Deletes each local branch whose remote tracking branch is gone.
 #
-# Deps:: env, git-bd, git-bg, sh, xargs
+# Deps:: bash, env, git-bd, git-bg, xargs
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git-bg | xargs --no-run-if-empty git-bd
diff --git a/git/command/branch/bin/git-bha b/git/command/branch/bin/git-bha
--- a/git/command/branch/bin/git-bha
+++ b/git/command/branch/bin/git-bha
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Branch command
 # ==================
@@ -6,8 +6,9 @@
 #
 # Sets the default branch marker of the given remote by querying it.
 #
-# Deps:: env, git-remote, sh
+# Deps:: bash, env, git-remote
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git remote set-head --auto "${@}"
diff --git a/git/command/checkout/bin/git-g b/git/command/checkout/bin/git-g
--- a/git/command/checkout/bin/git-g
+++ b/git/command/checkout/bin/git-g
@@ -1,12 +1,13 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Checkout command
 # ====================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-checkout, sh
+# Deps:: bash, env, git-checkout
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 # Toggle branches by default, i.e. switch from the current to the
 # previous branch unless another Git checkout operation is chosen by
diff --git a/git/command/checkout/bin/git-gg b/git/command/checkout/bin/git-gg
--- a/git/command/checkout/bin/git-gg
+++ b/git/command/checkout/bin/git-gg
@@ -1,14 +1,15 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Checkout command
 # ====================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-checkout, sh
+# Deps:: bash, env, git-checkout
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-main() {
+function main {
   local remote="${1:-origin}"
   local default_branch="$(git rev-parse --abbrev-ref "${remote}/HEAD")"
   git checkout "${default_branch#"${remote}/"}"
diff --git a/git/command/checkout/bin/git-gp b/git/command/checkout/bin/git-gp
--- a/git/command/checkout/bin/git-gp
+++ b/git/command/checkout/bin/git-gp
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Checkout command
 # ====================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-checkout, sh
+# Deps:: bash, env, git-checkout
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git checkout --patch "${@}"
diff --git a/git/command/cherry-pick/bin/git-xcp b/git/command/cherry-pick/bin/git-xcp
--- a/git/command/cherry-pick/bin/git-xcp
+++ b/git/command/cherry-pick/bin/git-xcp
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Cherry-pick command
 # =======================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-cherry-pick, sh
+# Deps:: bash, env, git-cherry-pick
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git cherry-pick "${@}"
diff --git a/git/command/cherry/bin/git-xcv b/git/command/cherry/bin/git-xcv
--- a/git/command/cherry/bin/git-xcv
+++ b/git/command/cherry/bin/git-xcv
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Cherry command
 # ==================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-cherry, sh
+# Deps:: bash, env, git-cherry
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git cherry -v "${@}"
diff --git a/git/command/commit/bin/git-cec b/git/command/commit/bin/git-cec
--- a/git/command/commit/bin/git-cec
+++ b/git/command/commit/bin/git-cec
@@ -1,18 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Commit command
 # ==================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-commit, sh
+# Deps:: bash, env, git-commit
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-main() {
-  local of_commit="${1:-HEAD}"
-  shift $(($#-($#${1+-1})))
-  git commit --edit --reedit-message="${of_commit}" ${GIT_X_SIGNOFF:-} \
-    --reset-author "${@}"
-}
-
-main "${@}"
+git commit --edit --reedit-message="${1:-HEAD}" ${GIT_X_SIGNOFF:-} --reset-author "${@:2}"
diff --git a/git/command/commit/bin/git-cqe b/git/command/commit/bin/git-cqe
--- a/git/command/commit/bin/git-cqe
+++ b/git/command/commit/bin/git-cqe
@@ -1,20 +1,18 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Commit command
 # ==================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-commit, sh
+# Deps:: bash, env, git-commit
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-main() {
+function main {
   local commit="${1:-HEAD~1}"
   local of_commit="${2:-${commit}}"
-  shift $(($#-($#${1+-1}${2+-1})))
-  git commit --squash="${commit}" --edit \
-    --reedit-message="${of_commit}" ${GIT_X_SIGNOFF:-} --reset-author \
-    "${@}"
+  git commit --squash="${commit}" --edit --reedit-message="${of_commit}" ${GIT_X_SIGNOFF:-} --reset-author "${@:3}"
 }
 
 main "${@}"
diff --git a/git/command/diff/bin/git-dnsf b/git/command/diff/bin/git-dnsf
--- a/git/command/diff/bin/git-dnsf
+++ b/git/command/diff/bin/git-dnsf
@@ -1,18 +1,13 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Diff command
 # ================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-diff, sh
+# Deps:: bash, env, git-diff
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-main() {
-  local filter="${1:-ACDMRTUXB}"
-  shift $(($#-($#${1+-1})))
-  cd "${GIT_PREFIX:-.}"
-  git diff --name-status --diff-filter="${filter}" "${@}"
-}
-
-main "${@}"
+cd "${GIT_PREFIX:-.}"
+git diff --name-status --diff-filter="${1:-ACDMRTUXB}" "${@:2}"
diff --git a/git/command/diff/bin/git-dsdu b/git/command/diff/bin/git-dsdu
--- a/git/command/diff/bin/git-dsdu
+++ b/git/command/diff/bin/git-dsdu
@@ -1,18 +1,13 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Diff command
 # ================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-diff, sh
+# Deps:: bash, env, git-diff
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-main() {
-  local commit="${1:-HEAD}"
-  shift $(($#-($#${1+-1})))
-  cd "${GIT_PREFIX:-.}"
-  git diff --dirstat "${commit}@{upstream}" "${@}"
-}
-
-main "${@}"
+cd "${GIT_PREFIX:-.}"
+git diff --dirstat "${1:-HEAD}@{upstream}" "${@:2}"
diff --git a/git/command/edit/bin/git-edit b/git/command/edit/bin/git-edit
--- a/git/command/edit/bin/git-edit
+++ b/git/command/edit/bin/git-edit
@@ -1,16 +1,17 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Edit command
 # ================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-config, sh
+# Deps:: bash, env, git-config
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-main() {
+function main {
   local editor="$(git config core.editor)"
-  ${editor:-${VISUAL:-${EDITOR:-true}}} "${@}"
+  "${editor:-${VISUAL:-${EDITOR:-true}}}" "${@}"
 }
 
 main "${@}"
diff --git a/git/command/edit/bin/git-eup b/git/command/edit/bin/git-eup
--- a/git/command/edit/bin/git-eup
+++ b/git/command/edit/bin/git-eup
@@ -1,12 +1,13 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Edit command
 # ================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-diff, git-edit, parallel, sh
+# Deps:: bash, env, git-diff, git-edit, parallel
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git diff --name-only --diff-filter=U -z \
   | parallel --tty -Xj1 --no-run-if-empty --max-args=10 --null git edit
diff --git a/git/command/help/bin/git-hg b/git/command/help/bin/git-hg
--- a/git/command/help/bin/git-hg
+++ b/git/command/help/bin/git-hg
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Help command
 # =================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-help, sh
+# Deps:: bash, env, git-help
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git help --guide "${@}"
diff --git a/git/command/log/bin/git-l b/git/command/log/bin/git-l
--- a/git/command/log/bin/git-l
+++ b/git/command/log/bin/git-l
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Log command
 # ===============
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-log, sh
+# Deps:: bash, env, git-log
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git log "${@}"
diff --git a/git/command/log/bin/git-la b/git/command/log/bin/git-la
--- a/git/command/log/bin/git-la
+++ b/git/command/log/bin/git-la
@@ -1,22 +1,22 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Log command
 # ===============
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-log, sh
-
-set -o errexit -o nounset
-
-# Log commits after date, no merge commits.
+# Logs commits after date, no merge commits.
 #
+# Deps:: bash, env, git-log
+
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
+
 main() {
-  local date="${1:-today}"
-  local commit="${2:-HEAD}"
-  shift $(($#-($#${1+-1}${2+-1})))
-  cd "${GIT_PREFIX:-.}"
-  git log --after="${date}" --no-merges --oneline --decorate=auto \
-    "${commit}" -- "${@:-.}"
+  local date="${1:-today}" commit="${2:-HEAD}" args="${@:3}"
+  (
+    cd "${GIT_PREFIX:-.}"
+    git log --after="${date}" --no-merges --oneline --decorate=auto "${commit}" -- "${args:-.}"
+  )
 }
 
 main "${@}"
diff --git a/git/command/log/bin/git-lcc b/git/command/log/bin/git-lcc
--- a/git/command/log/bin/git-lcc
+++ b/git/command/log/bin/git-lcc
@@ -1,22 +1,22 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Log command
 # ===============
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-config, git-log, sh
-
-set -o errexit -o nounset
-
-# Log commits of committer (self), no merge commits.
+# Logs commits of committer (self), no merge commits.
 #
+# Deps:: bash, env, git-config, git-log
+
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
+
 main() {
-  local author="${1:-$(git config user.email)}"
-  local commit="${2:-HEAD}"
-  shift $(($#-($#${1+-1}${2+-1})))
-  cd "${GIT_PREFIX:-.}"
-  git log --commiter="${author}" --no-merges --oneline --decorate=auto \
-    "${commit}" -- "${@:-.}"
+  local author="${1:-$(git config user.email)}" commit="${2:-HEAD}" args="${@:3}"
+  (
+    cd "${GIT_PREFIX:-.}"
+    git log --commiter="${author}" --no-merges --oneline --decorate=auto "${commit}" -- "${args:-.}"
+  )
 }
 
 main "${@}"
diff --git a/git/command/log/bin/git-lnv b/git/command/log/bin/git-lnv
--- a/git/command/log/bin/git-lnv
+++ b/git/command/log/bin/git-lnv
@@ -1,13 +1,14 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Log command
 # ===============
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-log, sh
-
-set -o errexit -o nounset
-
-# Log nth commit's cryptograhpic signature.
+# Logs nth commit's cryptograhpic signature.
 #
+# Deps:: bash, env, git-log
+
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
+
 git log --max-count=1 --oneline --show-signature "${@}"
diff --git a/git/command/log/bin/git-lrc b/git/command/log/bin/git-lrc
--- a/git/command/log/bin/git-lrc
+++ b/git/command/log/bin/git-lrc
@@ -1,11 +1,14 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Log command
 # ===============
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-rev-list, sh
+# Lists root commit (to log).
+#
+# Deps:: bash, env, git-rev-list
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git rev-list --max-parents=0 HEAD
diff --git a/git/command/merge/bin/git-msv b/git/command/merge/bin/git-msv
--- a/git/command/merge/bin/git-msv
+++ b/git/command/merge/bin/git-msv
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Merge command
 # =================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-merge, sh
+# Deps:: bash, env, git-merge
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git merge --squash --verify-signatures ${GIT_X_SIGNOFF:-} "${@}"
diff --git a/git/command/misc/bin/git-repo b/git/command/misc/bin/git-repo
--- a/git/command/misc/bin/git-repo
+++ b/git/command/misc/bin/git-repo
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Repo command
 # ================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-count-objects, sh
+# Deps:: bash, env, git-count-objects
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git count-objects --verbose --human-readable
diff --git a/git/command/misc/bin/git-shunned b/git/command/misc/bin/git-shunned
--- a/git/command/misc/bin/git-shunned
+++ b/git/command/misc/bin/git-shunned
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Shunned command
 # ===================
@@ -9,8 +9,9 @@
 # `git shun` and not yet assumed changed again with
 # `git update-index --no-assume-unchanged` or `git heed`.
 #
-# Deps:: env, git-ls-files, grep, sh
+# Deps:: bash, env, git-ls-files, grep
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git ls-files -v "${@}" | grep '^[a-z?]'
diff --git a/git/command/rebase/bin/git-rfo b/git/command/rebase/bin/git-rfo
--- a/git/command/rebase/bin/git-rfo
+++ b/git/command/rebase/bin/git-rfo
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Rebase command
 # ==================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-rebase, sh
+# Deps:: bash, env, git-rebase
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git rebase --force-rebase ${GIT_X_SIGNOFF:-} --onto "${@}"
diff --git a/git/command/show/bin/git-v b/git/command/show/bin/git-v
--- a/git/command/show/bin/git-v
+++ b/git/command/show/bin/git-v
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Show command
 # =================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-show, sh
+# Deps:: bash, env, git-show
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git show "${@}"
diff --git a/git/command/stash/bin/git-svnof b/git/command/stash/bin/git-svnof
--- a/git/command/stash/bin/git-svnof
+++ b/git/command/stash/bin/git-svnof
@@ -1,17 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Stash command
 # =================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-stash, sh
+# Deps:: bash, env, git-stash
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-main() {
-  local filter="${1:-ACDMRTUXB}"
-  shift $(($#-($#${1+-1})))
-  git stash show --name-only --diff-filter="${filter}" "${@}"
-}
-
-main "${@}"
+git stash show --name-only --diff-filter="${1:-ACDMRTUXB}" "${@:2}"
diff --git a/git/command/stash/bin/git-svpw b/git/command/stash/bin/git-svpw
--- a/git/command/stash/bin/git-svpw
+++ b/git/command/stash/bin/git-svpw
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Stash command
 # =================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-stash, sh
+# Deps:: bash, env, git-stash
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git stash show --patch --word-diff=color "${@}"
diff --git a/git/command/status/bin/git-i b/git/command/status/bin/git-i
--- a/git/command/status/bin/git-i
+++ b/git/command/status/bin/git-i
@@ -1,11 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Status command
 # ==================
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, git-status, sh
+# Deps:: bash, env, git-status
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 git status "${@}"
diff --git a/git/command/tag/bin/git-tla b/git/command/tag/bin/git-tla
--- a/git/command/tag/bin/git-tla
+++ b/git/command/tag/bin/git-tla
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Show-ref command
 # ====================
@@ -6,9 +6,10 @@
 #
 # Lists annotated tags.
 #
-# Deps:: awk, env, git-show-ref, sh
+# Deps:: awk, bash, env, git-show-ref
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 # List tags. Drop commit IDs in first column. Keep tags in second
 # column. Keep annotated tags, i.e. their dereferenced form ending in
diff --git a/git/command/tag/bin/git-tll b/git/command/tag/bin/git-tll
--- a/git/command/tag/bin/git-tll
+++ b/git/command/tag/bin/git-tll
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Show-ref command
 # ====================
@@ -6,9 +6,10 @@
 #
 # Lists light-weight tags.
 #
-# Deps:: awk, env, git-show-ref, sh, uniq
+# Deps:: awk, bash, env, git-show-ref, uniq
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 # List tags. Drop commit IDs in first column. Keep tags in second
 # column. Strip prefix `refs/tags/` and suffix `^{}` from tags. Keep
diff --git a/git/command/tag/bin/git-tlra b/git/command/tag/bin/git-tlra
--- a/git/command/tag/bin/git-tlra
+++ b/git/command/tag/bin/git-tlra
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Git Ls-remote command
 # =====================
@@ -7,9 +7,10 @@
 # Lists annotated tags of given remote repository or `origin` by
 # default.
 #
-# Deps:: awk, env, git-ls-remote, sh
+# Deps:: awk, bash, env, git-ls-remote
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 # List remote tags. Drop commit IDs in first column. Keep tags in
 # second column. Keep annotated tags, i.e. their dereferenced form
