Set shell option inherit_errexit
Signed-off-by: Tim Friske <me@tifr.de>

diff --git a/clipboard/bin/cbc b/clipboard/bin/cbc
--- a/clipboard/bin/cbc
+++ b/clipboard/bin/cbc
@@ -9,8 +9,9 @@
 #
 # Deps:: env, pbpaste, sh, xclip, xsel
 
-# Ensure fail-fast execution.
-shopt -os nounset pipefail errexit errtrace
+# Ensure fail-fast script execution.
+shopt -s inherit_errexit
+shopt -so nounset pipefail errtrace errexit
 
 if (( "${#}" > 0 )); then
   echo >&2 "usage: cbc [< FILE | < <(PROCESS)]"
diff --git a/date/bin/epoch b/date/bin/epoch
--- a/date/bin/epoch
+++ b/date/bin/epoch
@@ -12,8 +12,9 @@
 #
 # Deps:: bash, date, env
 
-# Ensure fail-fast execution.
-shopt -os nounset pipefail errexit errtrace
+# Ensure fail-fast script execution.
+shopt -s inherit_errexit
+shopt -so nounset pipefail errtrace errexit
 
 if [[ -t 1 ]]; then
   date '+epoch: %ss'
