Use Bash syntax in Bash scripts
Signed-off-by: Tim Friske <me@tifr.de>

diff --git a/clipboard/bin/cbc b/clipboard/bin/cbc
--- a/clipboard/bin/cbc
+++ b/clipboard/bin/cbc
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Cbc command
 # ===========
@@ -10,23 +10,21 @@
 #
 # Deps:: env, pbpaste, sh, xclip, xsel
 
-set -o errexit -o nounset
+# Ensure fail-fast execution.
+shopt -os nounset pipefail errexit errtrace
 
-main() {
-  if [ "${#}" -gt 0 ]; then
-    echo >&2 "usage: cbc [< FILE | < <(PROCESS)]"
-    echo >&2 "usage: PROCESS | cbc"
-    exit 1
-  fi
-  if command -v xclip >/dev/null 2>&1; then
-    xclip -selection clipboard -in
-  elif command -v xsel >/dev/null 2>&1; then
-    xsel --clipboard --input
-  elif command -v pbcopy >/dev/null 2>&1; then
-    pbcopy
-  else
-    echo Please install xclip, xsel or pbcopy.
-  fi
-}
+if (( "${#}" > 0 )); then
+  echo >&2 "usage: cbc [< FILE | < <(PROCESS)]"
+  echo >&2 "usage: PROCESS | cbc"
+  exit 1
+fi
 
-main "${@}"
+if command -v xclip &> /dev/null; then
+  xclip -selection clipboard -in
+elif command -v xsel &> /dev/null; then
+  xsel --clipboard --input
+elif command -v pbcopy &> /dev/null; then
+  pbcopy
+else
+  echo Please install xclip, xsel or pbcopy.
+fi
diff --git a/date/bin/epoch b/date/bin/epoch
--- a/date/bin/epoch
+++ b/date/bin/epoch
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Date command
 # ============
@@ -10,11 +10,12 @@
 # Prints `epoch: SECONDSs` if standard output file descriptor is
 # connected to terminal, else just `SECONDS`.
 #
-# Deps:: date, env, sh
+# Deps:: bash, date, env
 
-set -o errexit -o nounset
+# Ensure fail-fast execution.
+shopt -os nounset pipefail errexit errtrace
 
-if [ -t 1 ]; then
+if [[ -t 1 ]]; then
   date '+epoch: %ss'
 else
   date '+%s'
diff --git a/date/bin/ltz-off b/date/bin/ltz-off
--- a/date/bin/ltz-off
+++ b/date/bin/ltz-off
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Date command
 # ============
@@ -10,9 +10,10 @@
 # Prints `date-ltz-off: OFFSET` if standard output file descriptor is
 # connected to terminal, else just `OFFSET`.
 #
-# Deps:: date, env, sh
+# Deps:: bash, date, env
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-[ -t 1 ] && printf 'date-ltz-off: '
+[[ -t 1 ]] && printf 'date-ltz-off: '
 date '+%z'
diff --git a/date/bin/timer b/date/bin/timer
--- a/date/bin/timer
+++ b/date/bin/timer
@@ -9,24 +9,16 @@
 #
 # Deps:: bash, date, env
 
-timestamp() {
-  date +%s
-}
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-timestamp_to_date() {
-  date --date="@${1}"
-}
+function timestamp { date +%s; }
+function timestamp_to_date { date --date="@${1}"; }
+function timestamp_to_duration { date --utc --date="@${1}" +%H:%M:%S; }
+function press_key { read -rsn1 -p "timer: Press any key to stop."; echo; }
 
-timestamp_to_duration() {
-  date --utc --date="@${1}" +%H:%M:%S
-}
-
-press_key() {
-  read -rsn1 -p "timer: Press any key to stop."; echo
-}
-
-main() {
-  if [ "${#}" -ne 0 ]; then
+function main {
+  if (( "${#}" != 0 )); then
     echo "usage: timer"
     exit 1
   fi
diff --git a/date/bin/week b/date/bin/week
--- a/date/bin/week
+++ b/date/bin/week
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Date command
 # ============
@@ -7,11 +7,12 @@
 # Shows calendar week of year. Prints `week: WEEK` if standard output
 # file descriptor is connected to terminal, else just `WEEK`.
 #
-# Deps:: date, env, sh
+# Deps:: bash, date, env
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-if [ -t 1 ]; then
+if [[ -t 1 ]]; then
   date '+week: %V'
 else
   date '+%V'
diff --git a/gnupg/bin/gpg-agent-reload b/gnupg/bin/gpg-agent-reload
--- a/gnupg/bin/gpg-agent-reload
+++ b/gnupg/bin/gpg-agent-reload
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # GPG Agent Reload command
 # ========================
@@ -6,9 +6,10 @@
 #
 # Reloads the GPG agent, e.g. to tell it to forget cached passphrases.
 #
-# Deps:: env, gpg-connect-agent, sh
+# Deps:: bash, env, gpg-connect-agent
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 echo Reloading GPG agent...
 echo RELOADAGENT | gpg-connect-agent
diff --git a/gnupg/bin/gpg-agent-tty b/gnupg/bin/gpg-agent-tty
--- a/gnupg/bin/gpg-agent-tty
+++ b/gnupg/bin/gpg-agent-tty
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # GPG Agent TTY command
 # =====================
@@ -7,9 +7,10 @@
 # Updates the GPG agent's TTY in order to tell it on which TTY to prompt
 # the user for passphrases.
 #
-# Deps:: env, gpg-connect-agent, sh
+# Deps:: bash, env, gpg-connect-agent
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 echo Updating GPG TTY...
 echo UPDATESTARTUPTTY | gpg-connect-agent
diff --git a/gnupg/bin/gpg-list-keys-in-file b/gnupg/bin/gpg-list-keys-in-file
--- a/gnupg/bin/gpg-list-keys-in-file
+++ b/gnupg/bin/gpg-list-keys-in-file
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # GPG List Keys In File command
 # =============================
@@ -8,8 +8,9 @@
 # keyring. This command supports all the file formats the GnuPG program
 # does support.
 #
-# Deps:: env, gpg, sh
+# Deps:: env, gpg
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 gpg --show-keys --with-fingerprint --with-keygrip "${@}"
diff --git a/tmux/bin/tmux-pwd b/tmux/bin/tmux-pwd
--- a/tmux/bin/tmux-pwd
+++ b/tmux/bin/tmux-pwd
@@ -1,16 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Tmux PWD
 # ========
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, sh, tmux
+# Deps:: bash, env, tmux
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-main() {
-  tmux set-environment -g PWD "${PWD}"
-}
-
-main "${@}"
-
+tmux set-environment -g PWD "${PWD}"
diff --git a/util/bin/chmox b/util/bin/chmox
--- a/util/bin/chmox
+++ b/util/bin/chmox
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Chmox command
 # =============
@@ -10,8 +10,9 @@
 # usually requires super user privileges which can be obtained with
 # `sudo` and/or `su`.
 #
-# Deps:: chmod, env, sh
+# Deps:: bash, chmod, env
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 chmod --preserve-root --changes -- a+x "${@}"
diff --git a/util/bin/fix-trailing-whitespace b/util/bin/fix-trailing-whitespace
--- a/util/bin/fix-trailing-whitespace
+++ b/util/bin/fix-trailing-whitespace
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Fix Trailing Whitespace command
 # ===============================
@@ -7,8 +7,9 @@
 # Delete any whitespace after the last printable character and before
 # the end of a line of each given text file.
 #
-# Deps:: env, sed, sh
+# Deps:: bash, env, sed
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 sed --regexp-extended --expression='s/[[:space:]]*$//' --in-place "${@}"
diff --git a/util/bin/map b/util/bin/map
--- a/util/bin/map
+++ b/util/bin/map
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Map command
 # ===========
@@ -8,8 +8,9 @@
 # alias `map` resembles the well-known mathematical term `mapping' also
 # known as `map'.
 #
-# Deps:: env, sh, xargs
+# Deps:: bash, env, xargs
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 xargs --max-args=1 --no-run-if-empty "${@}"
diff --git a/util/bin/misses b/util/bin/misses
--- a/util/bin/misses
+++ b/util/bin/misses
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Misses command
 # ==============
@@ -6,8 +6,9 @@
 #
 # Lists files without matching content. Use `hits` for the opposite.
 #
-# Deps:: env, rg, sh
+# Deps:: bash, env, rg
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 rg --files-without-match --smart-case "${@}"
diff --git a/util/bin/os-systemd b/util/bin/os-systemd
--- a/util/bin/os-systemd
+++ b/util/bin/os-systemd
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Operating System Information command
 # ====================================
@@ -8,8 +8,9 @@
 #
 # Tim Friske <me@tifr.de>
 #
-# Deps:: env, sh, hostnamectl
+# Deps:: bash, env, hostnamectl
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 hostnamectl status
diff --git a/util/bin/rrf b/util/bin/rrf
--- a/util/bin/rrf
+++ b/util/bin/rrf
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Remove command
 # ==============
@@ -8,8 +8,9 @@
 # Remove directories and their contents recursively. Do not remove the
 # root directory and everything below it. Explain what is being done.
 #
-# Deps:: env, rm, sh
+# Deps:: bash, env, rm
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 rm --preserve-root --recursive --force --verbose "${@}"
diff --git a/util/bin/text-files b/util/bin/text-files
--- a/util/bin/text-files
+++ b/util/bin/text-files
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Text files command
 # ==================
@@ -6,9 +6,10 @@
 #
 # Search for text files, i.e. non-binary files.
 #
-# Deps:: env, find, grep, sh, xargs
+# Deps:: bash, env, find, grep, xargs
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
 find "${@}" -type f -print0 \
   | xargs --null --no-run-if-empty -- \
diff --git a/util/bin/upper-case b/util/bin/upper-case
--- a/util/bin/upper-case
+++ b/util/bin/upper-case
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Upper Case Conversion command
 # =============================
@@ -7,25 +7,17 @@
 # Convert characters read from standard input stream or command line
 # arguments to uppercase and print them to standard output stream.
 #
-# Deps:: awk, env, sh
+# Deps:: awk, bash, env
 
-set -o errexit -o nounset
+# Ensure fail-fast script execution.
+shopt -os nounset pipefail errexit errtrace
 
-uppercase() {
-  # `tr '[:lower:]' '[:upper:]'` only works for ASCII [a-z].
-  awk '{print toupper($0)}'
-}
+# `tr '[:lower:]' '[:upper:]'` only works for ASCII [a-z].
+function uppercase { awk '{print toupper($0)}'; }
+function newlines { printf '%s\n' "${@}"; }
 
-newlines() {
-  printf '%s\n' "${@}"
-}
-
-main() {
-  if [ "${#}" -eq 0 ]; then
-    uppercase
-  else
-    newlines "${@}" | uppercase
-  fi
-}
-
-main "${@}"
+if (( "${#}" == 0 )); then
+  uppercase
+else
+  newlines "${@}" | uppercase
+fi
